sudo : required
services:
    - docker

 deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: flask-app
    env: FlaskApp-env
    bucket_name: elasticbeanstalk-us-west-2-533316587000
    bucket_path: flask-app
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
