sudo: required

services:
    - docker

before_install:
    - pip install docker-compose

script:
    - docker-compose run service-2 sh -c "pytest"

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker-compose build

    - docker push srinivask61/flask-service1

    - docker push srinivask61/flask-service2

    - docker push srinivask61/flask-mongo

    - docker push srinivask61/flask-nginx
deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: flask-app
    env: FlaskApp-env
    bucket_name: elasticbeanstalk-us-west-2-533316587000
    bucket_path: flask-app
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
